### PR TITLE
Fixed seeding

### PR DESCRIPTION
**Pull request by malyna2**

### CODE REVIEW

**Review by KateYatsiuk — APPROVED** [review]

**Comment by KateYatsiuk** [comment]
Why not to add await _app.SeedDataAsync();_ line into _if (app.Environment.EnvironmentName == "Local")_ in Program.cs file?

**Review by BohdanBybliv — APPROVED** [review]

**Review by KateYatsiuk — APPROVED** [review]
Now both seeded streetcodes can be updated without any problems. Thanks!

**Review by KateYatsiuk — CHANGES_REQUESTED** [review]
One more comment. Something's wrong with field "Авторство" in the seeded streetcodes. Please pay attention to the screenshots below:
image
image

1 screenshot — new streetcode
2 screenshot — existing streetcode (AdditionalText in DB is NULL now. When AdditionalText is '' in DB, everything is OK).

Please, locate the problem and decide whether it would be better to make appropriate changes in the front-end part or here.

**Review by KateYatsiuk — APPROVED** [review]
Well done!

**Pull request merged**
