### PR TITLE
Fix integrated tests valerii

### PR DESCRIPTION
**Pull request by ValDekh**
## Summary of issue

[#828](https://github.com/ita-social-projects/StreetCode/issues/828)

## Summary of change

Fix all integrated test

### CODE REVIEW

**Review by KateYatsiuk — APPROVED** [review]
Please, fix SonarCloud error.
Moreover, (screenshots) pay attention to the fully commented test for the blob storage method, which we don't seem to be using. Can we remove this one and get rid of the commented test file?
Path: StreetCode\Streetcode\Streetcode.BLL\Services\BlobStorageService\BlobService.cs
image
Test file:
image

**Comment by ValDekh** [comment]
> Please, fix SonarCloud error. Moreover, (screenshots) pay attention to the fully commented test for the blob storage method, which we don't seem to be using. Can we remove this one and get rid of the commented test file? Path: StreetCode\Streetcode\Streetcode.BLL\Services\BlobStorageService\BlobService.cs image Test file: image

About  SonarCloud error - these errors are not related to the given task. Moreover, their correction may cause additional problems during execution of code. 
CleanBlob method and test have been removed.

**Review by mykola-krai — CHANGES_REQUESTED** [review]
image
Some integration tests failed (see attached image).

**Comment by Oleh-Kril** [comment]
First run on just created database:
Screenshot 2023-12-08 at 1 15 47 PM


All other runs after first:
Screenshot 2023-12-08 at 1 16 02 PM

Please investigate this

**Pull request merged**
